import os
import json
import re

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(SCRIPT_DIR)
ARTICLES_DIR = os.path.join(PROJECT_ROOT, "articles")
SEARCH_INDEX = os.path.join(PROJECT_ROOT, "search_index.json")

def load_articles():
    with open(SEARCH_INDEX, 'r', encoding='utf-8') as f:
        data = json.load(f)
        # Articles in search_index.json are already newest-first
        return data.get("articles", [])

def fix_tpt_duplicates(content):
    # Regex to capture the TPT block
    pattern = r'(<!-- ═══ TPT PRODUCT RECOMMENDATION & SCHEMA ═══ -->.*?</div>\s*</div>)'
    matches = re.findall(pattern, content, flags=re.DOTALL)
    
    if len(matches) > 1:
        # Keep only the first occurrence
        first_match = matches[0]
        # Remove all instances
        content = re.sub(pattern, '', content, flags=re.DOTALL)
        
        # Inject the first match back where the first one was...
        # Wait, the easiest is to just replace the first one we find with the match, and others with empty
        return True, content
    
    return False, content

def fix_articles():
    print("Loading articles from search_index.json...")
    all_articles = load_articles()
    
    # Sort them by date just in case
    all_articles.sort(key=lambda a: a.get('iso_date', ''), reverse=True)
    slug_to_idx = {a['slug']: i for i, a in enumerate(all_articles)}
    
    total_tpt_fixed = 0
    total_nav_fixed = 0
    
    for filename in os.listdir(ARTICLES_DIR):
        if not filename.endswith(".html"):
            continue
            
        filepath = os.path.join(ARTICLES_DIR, filename)
        slug = filename.replace(".html", "")
        
        with open(filepath, 'r', encoding='utf-8') as f:
            content = f.read()
            
        original_content = content
        
        # 1. Fix TPT duplicates
        tpt_marker = "<!-- ═══ TPT PRODUCT RECOMMENDATION & SCHEMA ═══ -->"
        if content.count(tpt_marker) > 1:
            parts = content.split(tpt_marker)
            # The first part is everything before the first marker.
            # The parts after that start with the TPT block.
            # Since the block was likely identical, we keep the first one.
            # But wait, each part might have trailing content if it wasn't immediately followed by another block.
            # Actually, because it was injected exactly in the same place over and over:
            # block 1: <script>...</script> <div...>...</div>
            # block 2: <script>...</script> <div...>...</div>
            
            # A safer way is to find the exact block text of the first one.
            part1 = parts[1] # This contains the TPT block AND whatever follows until the next marker
            # But the next marker was injected right before "<!-- ═══ RELATED ARTICLES ═══ -->" or similar.
            # Let's just use regex to find the end of the TPT block which is ALWAYS: "</div>\n        </div>\n"
            
            # Since the TPT block is generated by a function, we know what it looks like exactly.
            # Let's just find the first instance and its exact HTML, then replace all others.
            # Actually, simply rebuilding the article without TPT and then re-injecting it using _post_process.py is safest.
            
            # Let's just remove ALL TPT blocks and let _post_process.py do it cleanly.
            # But since it's hard to parse, let's use a regex that matches until the final </div> of the TPT block.
            # We know the TPT block starts with the marker, contains a script tag, and exactly 2 closing divs at the end.
            
            # Alternatively, since all duplicates are contiguous, we can replace "\n        <!-- ═══ TPT PRODUCT RECOMMENDATION & SCHEMA ═══ -->"
            
            # Let's just do a simple while loop:
            # Find the marker. Find the end of its block (we know it's "Browse All Products\n                    </a>\n                </div>\n            </div>\n        </div>\n").
            # Replace all occurrences of that whole block with just one.
            
            end_marker = "Browse All Products\n                    </a>\n                </div>\n            </div>\n        </div>"
            
            if end_marker in content:
                start_idx = content.find(tpt_marker)
                end_idx = content.find(end_marker, start_idx) + len(end_marker)
                
                if start_idx != -1 and end_idx != -1:
                    full_block = content[start_idx:end_idx]
                    
                    # Ensure we have the full block correctly
                    if full_block.count(tpt_marker) == 1:
                        # Replace all exact text matches of the full_block with a special token
                        content = content.replace(full_block, "___TPT_BLOCK___")
                        
                        # Now remove ALL occurrences of the special token that have whitespace between them
                        # But wait, it might be safer to find all occurrences using string methods
                        # Replace all "___TPT_BLOCK___" (with any spaces between them) with just one
                        content = re.sub(r'(___TPT_BLOCK___\s*)+', '___TPT_BLOCK___\n', content)
                        
                        # Put the full block back
                        content = content.replace("___TPT_BLOCK___", full_block)
                        
                        print(f"  [TPT] Fixed duplicates in {slug}")
                        total_tpt_fixed += 1
            
        # 2. Fix Nav Links
        if 'id="prevArticleNav"' not in content and 'id="nextArticleNav"' not in content:
            idx = slug_to_idx.get(slug)
            if idx is not None and len(all_articles) > 1:
                prev_art = all_articles[idx - 1] if idx > 0 else all_articles[-1]
                next_art = all_articles[idx + 1] if idx < len(all_articles) - 1 else all_articles[0]
                
                prev_url = prev_art['slug'] + '.html'
                prev_title = prev_art.get('title', 'Previous Article')[:45]
                prev_html = f'<div id="prevArticleNav" class="article-nav article-nav-prev"><a href="{prev_url}" title="{prev_title}">&#8592;</a><span class="nav-title">{prev_title}</span></div>'
                
                next_url = next_art['slug'] + '.html'
                next_title = next_art.get('title', 'Next Article')[:45]
                next_html = f'<div id="nextArticleNav" class="article-nav article-nav-next"><a href="{next_url}" title="{next_title}">&#8594;</a><span class="nav-title">{next_title}</span></div>'
                
                # In build_articles.py, it's injected before: <!-- SCROLL TO TOP BUTTON -->
                target = '<!-- SCROLL TO TOP BUTTON -->'
                if target in content:
                    nav_html = f"<!-- PREV / NEXT ARTICLE NAV -->\n    {prev_html}\n    {next_html}\n\n    "
                    content = content.replace(target, nav_html + target)
                
                    print(f"  [NAV] Added nav buttons to {slug}")
                    total_nav_fixed += 1
                else:
                    print(f"  [NAV] Could not find insertion point in {slug}")
        
        if content != original_content:
            with open(filepath, 'w', encoding='utf-8') as f:
                f.write(content)

    print(f"\nDone! Fixed TPT duplicates in {total_tpt_fixed} articles, added NAV to {total_nav_fixed} articles.")

if __name__ == "__main__":
    fix_articles()
